// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hajushqiaibmyyqijodw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhanVzaHFpYWlibXl5cWlqb2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjk2OTYsImV4cCI6MjA2MTcwNTY5Nn0.rtyDB06fk09vT5uBvLH06qh-6wv-3k_PlN1bPPgMlkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);